# Generated by Django 5.0.3 on 2024-04-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_owner_task_is_completed_task_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
