# Generated by Django 5.0.3 on 2024-04-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_member_date_remove_task_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Project',
            new_name='project',
        ),
    ]
