# Generated by Django 5.0.3 on 2024-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
